[build]
  base = "frontend"
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

# Functions configuration
[functions]
  directory = "netlify/functions"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for Netlify functions
# Note: Set GMAIL_APP_PASSWORD in Netlify dashboard for security
[context.production.environment]
  GMAIL_USER = "hardikcp5@gmail.com"
  
[context.deploy-preview.environment]
  GMAIL_USER = "hardikcp5@gmail.com"
